/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ImageDto,
} from '../models/index';
import {
    ImageDtoFromJSON,
    ImageDtoToJSON,
} from '../models/index';

export interface AddImagesRequest {
    listingId: string;
    imageDto: Array<ImageDto>;
}

export interface GetImagesByListingRequest {
    listingId: string;
}

/**
 * 
 */
export class ImageControllerApi extends runtime.BaseAPI {

    /**
     */
    async addImagesRaw(requestParameters: AddImagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['listingId'] == null) {
            throw new runtime.RequiredError(
                'listingId',
                'Required parameter "listingId" was null or undefined when calling addImages().'
            );
        }

        if (requestParameters['imageDto'] == null) {
            throw new runtime.RequiredError(
                'imageDto',
                'Required parameter "imageDto" was null or undefined when calling addImages().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['listingId'] != null) {
            queryParameters['listingId'] = requestParameters['listingId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/images/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['imageDto']!.map(ImageDtoToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async addImages(requestParameters: AddImagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.addImagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getImagesByListingRaw(requestParameters: GetImagesByListingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ImageDto>>> {
        if (requestParameters['listingId'] == null) {
            throw new runtime.RequiredError(
                'listingId',
                'Required parameter "listingId" was null or undefined when calling getImagesByListing().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/images/byListing/{listingId}`.replace(`{${"listingId"}}`, encodeURIComponent(String(requestParameters['listingId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ImageDtoFromJSON));
    }

    /**
     */
    async getImagesByListing(requestParameters: GetImagesByListingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ImageDto>> {
        const response = await this.getImagesByListingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
