services:
  dreamhouse-app-db:
    image: postgres:17-alpine
    container_name: dreamhouse-app-db
    ports:
      - "1200:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dreamhouse-app-db-vol:/var/lib/postgresql/data
      - ./io-service/app_db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    networks:
      dreamhouse-auth-network:
      dreamhouse-app-network:

  dreamhouse-auth-db:
    image: postgres:17-alpine
    container_name: dreamhouse-auth-db
    ports:
      - "1201:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dreamhouse-auth-db-vol:/var/lib/postgresql/data
      - ./auth-service/auth_db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    networks:
      dreamhouse-auth-network:

  dreamhouse-db-manager:
    image: dpage/pgadmin4:9.3
    container_name: dreamhouse-db-manager
    user: "5050:5050"
    restart: always
    depends_on:
      - dreamhouse-auth-db
      - dreamhouse-app-db
    ports:
      - "1202:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dreamhouse.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      dreamhouse-auth-network:
      dreamhouse-app-network:

  dreamhouse-auth-service:
    image: quay.io/keycloak/keycloak:26.2
    container_name: dreamhouse-auth-service
    restart: always
    command: start
    depends_on:
      - dreamhouse-auth-db
    ports:
      - "1100:8080"
      - "1101:8443"
    environment:
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
      KC_DB: postgres
      KC_DB_SCHEMA: auth
      KC_DB_URL: jdbc:postgresql://dreamhouse-auth-db:5432/postgres?ssl=allow
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/dreamhouse.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/dreamhouse.key
    volumes:
      - dreamhouse-auth-data:/opt/keycloak/data
      - ./certificates/dreamhouse.crt:/opt/keycloak/conf/dreamhouse.crt
      - ./certificates/dreamhouse.key:/opt/keycloak/conf/dreamhouse.key
    networks:
      dreamhouse-auth-network:

  dreamhouse-app-listing-service:
    image: ciprian0411/dreamhouse-app-listing-service:0.0.1
    container_name: dreamhouse-app-listing-service
    restart: always
    depends_on:
      - dreamhouse-auth-db
      - dreamhouse-app-db
    ports:
      - "8080:8080"
    networks:
      dreamhouse-auth-network:
      dreamhouse-app-network:

  dreamhouse-app-user-service:
    image: ciprian0411/dreamhouse-app-user-service:0.0.1
    container_name: dreamhouse-app-user-service
    restart: always
    depends_on:
      - dreamhouse-auth-db
      - dreamhouse-app-db
    ports:
      - "8081:8081"
    networks:
      dreamhouse-auth-network:
      dreamhouse-app-network:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data

  dreamhouse-api-gateway:
    image: kong:3.9
    container_name: dreamhouse-api-gateway
    restart: always
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./api-gateway/kong.yml:/usr/local/kong/kong.yml
    networks:
      - dreamhouse-auth-network
      - dreamhouse-app-network

volumes:
  dreamhouse-app-db-vol:
  dreamhouse-auth-db-vol:
  dreamhouse-auth-data:
  pgadmin-data:
  portainer-data:

networks:
  dreamhouse-app-network:
  dreamhouse-auth-network: