services:
  dreamhouse-db:
    build:
      context: ./dreamhouse/src/main/resources/db
      dockerfile: Dockerfile
    container_name: dreamhouse-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dreamhouse-db-vol:/var/lib/postgresql/data
    networks:
      dreamhouse-auth-network:
      dreamhouse-app-network:

  dreamhouse-auth-service:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    command: start
    depends_on:
      - dreamhouse-db
    ports:
      - "9990:8080"
      - "9991:8443"
    environment:
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME: localhost
      KC_PROXY: edge
      KC_HTTP_ENABLED: true
      DB: postgres
      DB_URL: jdbc:postgresql://postgres:5432/postgresql?ssl=allow
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/dreamhouse.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/dreamhouse.key
    volumes:
      - ./certificates/dreamhouse.crt:/opt/keycloak/conf/dreamhouse.crt
      - ./certificates/dreamhouse.key:/opt/keycloak/conf/dreamhouse.key
    networks:
      dreamhouse-auth-network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.entrypoints=http"
      - "traefik.http.routers.keycloak.rule=Host(`localhost`)"
      - "traefik.http.middlewares.keycloak-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.keycloak.middlewares=keycloak-https-redirect"
      - "traefik.http.routers.keycloak-secure.entrypoints=https"
      - "traefik.http.routers.keycloak-secure.rule=Host(`localhost`)"
      - "traefik.http.routers.keycloak-secure.tls=true"
      - "traefik.http.routes.keycloak-secure.service=keycloak"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"

volumes:
  dreamhouse-db-vol:
networks:
  dreamhouse-auth-network:
  dreamhouse-app-network: