services:
  dreamhouse-app-db:
    image: postgres:17-alpine
    container_name: dreamhouse-app-db
    ports:
      - "1200:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dreamhouse-app-db-vol:/var/lib/postgresql/data
      - ./dreamhouse/src/main/resources/db/DataBase.sql:/docker-entrypoint-initdb.d/db_init.sql
    networks:
      dreamhouse-auth-network:
      dreamhouse-app-network:

  dreamhouse-auth-db:
    image: postgres:17-alpine
    container_name: dreamhouse-auth-db
    ports:
      - "1201:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dreamhouse-auth-db-vol:/var/lib/postgresql/data
    networks:
      dreamhouse-auth-network:

  dreamhouse-auth-service:
    image: quay.io/keycloak/keycloak:26.2
    container_name: dreamhouse-auth-service
    restart: always
    command: start
    depends_on:
      - dreamhouse-auth-db
    ports:
      - "1100:8080"
      - "1101:8443"
    environment:
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://dreamhouse-auth-db:5432/postgres?ssl=allow
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/dreamhouse.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/dreamhouse.key
    volumes:
      - dreamhouse-auth-data:/opt/keycloak/data
      - ./certificates/dreamhouse.crt:/opt/keycloak/conf/dreamhouse.crt
      - ./certificates/dreamhouse.key:/opt/keycloak/conf/dreamhouse.key
    networks:
      dreamhouse-auth-network:

volumes:
  dreamhouse-app-db-vol:
  dreamhouse-auth-db-vol:
  dreamhouse-auth-data:

networks:
  dreamhouse-app-network:
  dreamhouse-auth-network: