services:
  dreamhouse-db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dreamhouse-db-vol:/var/lib/postgresql/data
      - ./src/main/resources/db/DataBase.sql:/docker-entrypoint-initdb.d/db_init.sql

volumes:
  dreamhouse-db-vol:
