/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PurchaseRequest,
} from '../models/index';
import {
    PurchaseRequestFromJSON,
    PurchaseRequestToJSON,
} from '../models/index';

export interface CreateRequestRequest {
    listingId: string;
}

/**
 * 
 */
export class PurchaseRequestControllerApi extends runtime.BaseAPI {

    /**
     */
    async createRequestRaw(requestParameters: CreateRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PurchaseRequest>> {
        if (requestParameters['listingId'] == null) {
            throw new runtime.RequiredError(
                'listingId',
                'Required parameter "listingId" was null or undefined when calling createRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/requests/create/{listingId}`.replace(`{${"listingId"}}`, encodeURIComponent(String(requestParameters['listingId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PurchaseRequestFromJSON(jsonValue));
    }

    /**
     */
    async createRequest(requestParameters: CreateRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PurchaseRequest> {
        const response = await this.createRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
