/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Listing } from './Listing';
import {
    ListingFromJSON,
    ListingFromJSONTyped,
    ListingToJSON,
    ListingToJSONTyped,
} from './Listing';

/**
 * 
 * @export
 * @interface PurchaseRequest
 */
export interface PurchaseRequest {
    /**
     * 
     * @type {string}
     * @memberof PurchaseRequest
     */
    id?: string;
    /**
     * 
     * @type {Listing}
     * @memberof PurchaseRequest
     */
    listing?: Listing;
    /**
     * 
     * @type {User}
     * @memberof PurchaseRequest
     */
    requester?: User;
    /**
     * 
     * @type {string}
     * @memberof PurchaseRequest
     */
    message?: string;
    /**
     * 
     * @type {Date}
     * @memberof PurchaseRequest
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the PurchaseRequest interface.
 */
export function instanceOfPurchaseRequest(value: object): value is PurchaseRequest {
    return true;
}

export function PurchaseRequestFromJSON(json: any): PurchaseRequest {
    return PurchaseRequestFromJSONTyped(json, false);
}

export function PurchaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'listing': json['listing'] == null ? undefined : ListingFromJSON(json['listing']),
        'requester': json['requester'] == null ? undefined : UserFromJSON(json['requester']),
        'message': json['message'] == null ? undefined : json['message'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function PurchaseRequestToJSON(json: any): PurchaseRequest {
    return PurchaseRequestToJSONTyped(json, false);
}

export function PurchaseRequestToJSONTyped(value?: PurchaseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'listing': ListingToJSON(value['listing']),
        'requester': UserToJSON(value['requester']),
        'message': value['message'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

