server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: ["prometheus", "health", "info"]
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  application:
    name: dreamhouse-feedback-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:1200/postgres
    username: postgres
    password: postgres

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:1100/realms/dreamhouse
#          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
#      client:
#        registration:
#          keycloak:
#            client-id: backend-rest-api
#            client-secret:
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope: openid, profile, email
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:1100/realms/dreamhouse

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 9b12429aec3986
    password: d86c56ad6fe97b
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

jwt:
  auth:
    converter:
      resource-id: backend-rest-api
      principle-attribute: preferred_username

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: false
