scrape_configs:
  - job_name: 'dreamhouse-app-listing-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'dreamhouse-app-listing-service:8080' ]

  - job_name: 'dreamhouse-app-user-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'dreamhouse-app-user-service:8081' ]

  - job_name: 'dreamhouse-app-feedback-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'dreamhouse-app-feedback-service:8082' ]

  - job_name: 'dreamhouse-auth-service'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'dreamhouse-auth-service:9000' ]

  - job_name: 'dreamhouse-api-gateway'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'dreamhouse-api-gateway:8001' ]