server:
  port: 8080

spring:
  application:
    name: dreamhouse
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:1200/postgres
    username: postgres
    password: postgres

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:1101/realms/dreamhouse
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: backend-rest-api
      principle-attribute: preferred_username

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: false
    