server:
  port: 8080

spring:
  application:
    name: dreamhouse
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        default_schema: project
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        ddl-auto: none
    open-in-view: false

  flyway:
#    enabled: false
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    table: project_schema_version
    baseline-version: 0

vars:
    security:
      enable: true

admin:
  username: admin
  password: admin
  email: admin@admin.com


token:
  ttl: 3600000
  secret: "https://www.youtube.com/watch?v=VBUMYOYJISc"
