/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Listing } from './Listing';
import {
    ListingFromJSON,
    ListingFromJSONTyped,
    ListingToJSON,
    ListingToJSONTyped,
} from './Listing';
import type { FavoritesId } from './FavoritesId';
import {
    FavoritesIdFromJSON,
    FavoritesIdFromJSONTyped,
    FavoritesIdToJSON,
    FavoritesIdToJSONTyped,
} from './FavoritesId';

/**
 * 
 * @export
 * @interface Favorites
 */
export interface Favorites {
    /**
     * 
     * @type {FavoritesId}
     * @memberof Favorites
     */
    id?: FavoritesId;
    /**
     * 
     * @type {User}
     * @memberof Favorites
     */
    user?: User;
    /**
     * 
     * @type {Listing}
     * @memberof Favorites
     */
    listing?: Listing;
}

/**
 * Check if a given object implements the Favorites interface.
 */
export function instanceOfFavorites(value: object): value is Favorites {
    return true;
}

export function FavoritesFromJSON(json: any): Favorites {
    return FavoritesFromJSONTyped(json, false);
}

export function FavoritesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Favorites {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : FavoritesIdFromJSON(json['id']),
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'listing': json['listing'] == null ? undefined : ListingFromJSON(json['listing']),
    };
}

export function FavoritesToJSON(json: any): Favorites {
    return FavoritesToJSONTyped(json, false);
}

export function FavoritesToJSONTyped(value?: Favorites | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': FavoritesIdToJSON(value['id']),
        'user': UserToJSON(value['user']),
        'listing': ListingToJSON(value['listing']),
    };
}

