/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListingDto
 */
export interface ListingDto {
    /**
     * 
     * @type {string}
     * @memberof ListingDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ListingDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ListingDto
     */
    location?: string;
    /**
     * 
     * @type {number}
     * @memberof ListingDto
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof ListingDto
     */
    surface?: number;
    /**
     * 
     * @type {number}
     * @memberof ListingDto
     */
    rooms?: number;
}

/**
 * Check if a given object implements the ListingDto interface.
 */
export function instanceOfListingDto(value: object): value is ListingDto {
    return true;
}

export function ListingDtoFromJSON(json: any): ListingDto {
    return ListingDtoFromJSONTyped(json, false);
}

export function ListingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'location': json['location'] == null ? undefined : json['location'],
        'price': json['price'] == null ? undefined : json['price'],
        'surface': json['surface'] == null ? undefined : json['surface'],
        'rooms': json['rooms'] == null ? undefined : json['rooms'],
    };
}

export function ListingDtoToJSON(json: any): ListingDto {
    return ListingDtoToJSONTyped(json, false);
}

export function ListingDtoToJSONTyped(value?: ListingDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'location': value['location'],
        'price': value['price'],
        'surface': value['surface'],
        'rooms': value['rooms'],
    };
}

