/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FavoritesId
 */
export interface FavoritesId {
    /**
     * 
     * @type {string}
     * @memberof FavoritesId
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof FavoritesId
     */
    listingId?: string;
}

/**
 * Check if a given object implements the FavoritesId interface.
 */
export function instanceOfFavoritesId(value: object): value is FavoritesId {
    return true;
}

export function FavoritesIdFromJSON(json: any): FavoritesId {
    return FavoritesIdFromJSONTyped(json, false);
}

export function FavoritesIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavoritesId {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'listingId': json['listingId'] == null ? undefined : json['listingId'],
    };
}

export function FavoritesIdToJSON(json: any): FavoritesId {
    return FavoritesIdToJSONTyped(json, false);
}

export function FavoritesIdToJSONTyped(value?: FavoritesId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'listingId': value['listingId'],
    };
}

