/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageDto
 */
export interface ImageDto {
    /**
     * 
     * @type {string}
     * @memberof ImageDto
     */
    listingId?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageDto
     */
    imageUrl?: string;
}

/**
 * Check if a given object implements the ImageDto interface.
 */
export function instanceOfImageDto(value: object): value is ImageDto {
    return true;
}

export function ImageDtoFromJSON(json: any): ImageDto {
    return ImageDtoFromJSONTyped(json, false);
}

export function ImageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'listingId': json['listingId'] == null ? undefined : json['listingId'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
    };
}

export function ImageDtoToJSON(json: any): ImageDto {
    return ImageDtoToJSONTyped(json, false);
}

export function ImageDtoToJSONTyped(value?: ImageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listingId': value['listingId'],
        'imageUrl': value['imageUrl'],
    };
}

