/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewDto
 */
export interface ReviewDto {
    /**
     * 
     * @type {string}
     * @memberof ReviewDto
     */
    listingId?: string;
    /**
     * 
     * @type {number}
     * @memberof ReviewDto
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof ReviewDto
     */
    comment?: string;
    /**
     * 
     * @type {Date}
     * @memberof ReviewDto
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the ReviewDto interface.
 */
export function instanceOfReviewDto(value: object): value is ReviewDto {
    return true;
}

export function ReviewDtoFromJSON(json: any): ReviewDto {
    return ReviewDtoFromJSONTyped(json, false);
}

export function ReviewDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewDto {
    if (json == null) {
        return json;
    }
    return {
        
        'listingId': json['listingId'] == null ? undefined : json['listingId'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function ReviewDtoToJSON(json: any): ReviewDto {
    return ReviewDtoToJSONTyped(json, false);
}

export function ReviewDtoToJSONTyped(value?: ReviewDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listingId': value['listingId'],
        'rating': value['rating'],
        'comment': value['comment'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

