/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Favorites,
} from '../models/index';
import {
    FavoritesFromJSON,
    FavoritesToJSON,
} from '../models/index';

export interface AddFavoriteRequest {
    listingId: string;
}

export interface RemoveFavoriteRequest {
    userId: string;
    listingId: string;
}

/**
 * 
 */
export class FavoritesControllerApi extends runtime.BaseAPI {

    /**
     */
    async addFavoriteRaw(requestParameters: AddFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Favorites>> {
        if (requestParameters['listingId'] == null) {
            throw new runtime.RequiredError(
                'listingId',
                'Required parameter "listingId" was null or undefined when calling addFavorite().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['listingId'] != null) {
            queryParameters['listingId'] = requestParameters['listingId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/favorites/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FavoritesFromJSON(jsonValue));
    }

    /**
     */
    async addFavorite(requestParameters: AddFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Favorites> {
        const response = await this.addFavoriteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async removeFavoriteRaw(requestParameters: RemoveFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling removeFavorite().'
            );
        }

        if (requestParameters['listingId'] == null) {
            throw new runtime.RequiredError(
                'listingId',
                'Required parameter "listingId" was null or undefined when calling removeFavorite().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        if (requestParameters['listingId'] != null) {
            queryParameters['listingId'] = requestParameters['listingId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/favorites/remove`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async removeFavorite(requestParameters: RemoveFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removeFavoriteRaw(requestParameters, initOverrides);
    }

}
