/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * RegisterDTO model
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * 
 * @export
 * @interface RegisterDTO
 */
export interface RegisterDTO {
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    email: string;

    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    password: string;

    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    confirmPassword: string;

    /**
     * Optional full name
     * @type {string}
     * @memberof RegisterDTO
     */
    fullName?: string;
}

/**
 * Check if a given object implements the RegisterDTO interface.
 */
export function instanceOfRegisterDTO(value: object): value is RegisterDTO {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('confirmPassword' in value) || value['confirmPassword'] === undefined) return false;
    return true;
}

export function RegisterDTOFromJSON(json: any): RegisterDTO {
    return RegisterDTOFromJSONTyped(json, false);
}

export function RegisterDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterDTO {
    if (json == null) {
        return json;
    }
    return {
        email: json['email'],
        password: json['password'],
        confirmPassword: json['confirmPassword'],
        fullName: json['fullName'],
    };
}

export function RegisterDTOToJSON(value?: RegisterDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        email: value.email,
        password: value.password,
        confirmPassword: value.confirmPassword,
        fullName: value.fullName,
    };
}
