name: DreamHouse Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'dreamhouse-frontend-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'dreamhouse-frontend-service/**'

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get frontend version from package.json
        id: get_version
        working-directory: ./dreamhouse-frontend-service
        run: echo "::set-output name=version::$(jq -r .version package.json)"

      - name: Build and push frontend Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ciprian0411/dreamhouse-app-frontend-service
          tags: latest,${{ steps.get_version.outputs.version }}
          registry: docker.io
          dockerfile: ./dreamhouse-frontend-service/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
