# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DreamHouse Listing Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'dreamhouse-listing-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'dreamhouse-listing-service/**'

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v1
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven

    - name: Get listing service version from pom.xml
      id: get_version
      working-directory: ./dreamhouse-listing-service
      run: echo "::set-output name=version::$(mvn help:evaluate -q -Dexpression=project.version)"

    - name: Build listing service with Maven
      working-directory: ./dreamhouse-listing-service
      run: mvn clean install -DskipTests

    - name: Build and push listing service Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ciprian0411/dreamhouse-app-listing-service
        tags: latest,${{ steps.get_version.outputs.version }}
        registry: docker.io
        dockerfile: ./dreamhouse-listing-service/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
